### PR TITLE
Fix far viewing

### LINKED ISSUE #3802: Shift left mouse clicking the map in map view mode results in auto explore starting after you exit map view
**PLATFORM and OS or BROWSER:**

local tiles

**DCSS VERSION AND GAME INFORMATION:**

Version: 0.32-a0-1074-g4fd57f6e19

**DESCRIPTION:**

Pressing X to go into map view followed by shift left mouse clicking on the map won't no anything immediately, but will start auto explore when you press escape to exit map view.

**EXTRA FILES:**

### LINKED ISSUE #3804: Right mouse clicking the map and dragging in map view does nothing
**PLATFORM and OS or BROWSER:**

windows local tiles

**DCSS VERSION AND GAME INFORMATION:**

Versions where clicking and dragging does nothing: 0.32-a0-1074-g4fd57f6e19, 0.31.0, 0.30.2, 0.29.1, 0.28.0
Versions where dragging does nothing, but the initial click works: 0.27.1, 0.26.1

**DESCRIPTION:**

While in map view mode, you should be able to right mouse click the map to view that part of the map. You should then be able to drag the mouse around the map while holding the right mouse button to view different parts of the map. However, nothing happens when I do this.

**EXTRA FILES:**

### PR DESCRIPTION
**Pull request by WizardIke**
In local tiles while in map view mode, you should be able to right click and drag the mini map to view those parts of the map. However, in version 0.26 dragging the mouse stopped doing anything and in version 0.28 right clicking the map stopped doing anything.

Fixes #3804
Fixes #3802

### CODE REVIEW

File: crawl-ref/source/viewmap.cc [hunk 1]
```diff
@@ -873,6 +874,32 @@ class UIMapView : public ui::Widget
...
+    void start_far_viewing(coord_def viewed_location)
+    {
+        m_far_view = true;
+        update_far_viewing(viewed_location);
+    }
+
+    void stop_far_viewing()
+    {
+        m_far_view = false;
+
```
Comment (chucksellick) [inline crawl-ref/source/viewmap.cc:888]: There's this one out of place blank line here! Looks good tho. Noticed this issue myself and was thinking "I'm sure this used to work here"

File: crawl-ref/source/viewmap.cc [hunk 2]
```diff
@@ -975,12 +1004,38 @@ level_pos map_follow_stairs(bool up, const coord_def &pos)
...
+void stop_far_viewing()
+{
+    if (map_view)
+        map_view->stop_far_viewing();
 }
 
+bool is_far_viewing()
+{
+    if (!map_view)
```
Comment (chucksellick) [inline crawl-ref/source/viewmap.cc:1026]: Can condense the function into a single line

`return map_view && map_view->is_far_viewing()`

File: crawl-ref/source/viewmap.cc (hunk 1 above)
Comment (WizardIke) [reply crawl-ref/source/viewmap.cc]: Thanks, I've removed the bland line

File: crawl-ref/source/viewmap.cc (hunk 2 above)
Comment (WizardIke) [reply crawl-ref/source/viewmap.cc]: Done. That's definitely nicer to read
