### PR TITLE
Fix: don't list walljump twice while silenced

### LINKED ISSUE #2120: Reading a scroll of silence causes "Wall jump" button to appear twice
**PLATFORM and OS or BROWSER:**
Local tiles, macOS 11.5.2

**DCSS VERSION AND GAME INFORMATION:**
0.28-a0-419-g3dc288482e

**DESCRIPTION:**
Steps to reproduce:
1. Create a character, enter Wiz mode (for convince—this same issue occurred naturally in a game for me)
2. Give yourself a scroll of silence
3. Join WJC and set your piety to anything above about 50
4. Observe the set of buttons in the "Abilities" section of the sidebar
5. Read the scroll of silence
6. Observe the set of buttons in the "Abilities" section of the sidebar
   - Expected results: the buttons remained unchanged
   - Actual results: a second wall jump button appears, functionally identically to the first. It does not appear in the <kdb>a</kdb> menu, nor anywhere else that I can see.

Notes:
- I tested this with one other god and did not have the same issue

**EXTRA FILES:**
Before silenced:
image

After silenced:
image

Example save with the issue already-present (same turn as the above screenshot):
[PerryWiz.cs.zip](https://github.com/crawl/crawl/files/7122945/PerryWiz.cs.zip)

### PR DESCRIPTION
**Pull request by perryprog**
This specifically affected the "Abilities" section of the sidebar, but I'm not sure where else. It seems likely that this is legacy code from when walljump was more of a pseudo-ability, but since whether something can be used while silenced is determined by the failure basis (e.g., if it's an invocation), there's no need for this check to exist in get_god_abilities anymore.

Closes #2120.

### CODE REVIEW

File: crawl-ref/source/ability.cc [hunk 1]
```diff
@@ -3941,11 +3941,14 @@ vector<ability_type> get_god_abilities(bool ignore_silence, bool ignore_piety,
             abilities.push_back(static_cast<ability_type>(anc_type));
         }
     }
-    if (silenced(you.pos()) && you_worship(GOD_WU_JIAN) && piety_rank() >= 2)
-        abilities.push_back(ABIL_WU_JIAN_WALLJUMP);
 
     if (!ignore_silence && silenced(you.pos()))
+    {
+        if (you_worship(GOD_WU_JIAN) && piety_rank() >= 2)
```
Comment (gammafunk) [inline crawl-ref/source/ability.cc:3947]: You would probably want to do this like
```suggestion
        if (have_passive(passive_t::wu_jian_wall_jump))
```

Comment (perryprog) [reply crawl-ref/source/ability.cc:3947]: Nice. DIdn't know about that.
